export const FILTER_TERM_CHANGED = "FILTER_TERM_CHANGED";

export const ERROR_MODAL_CLOSED = "ERROR_MODAL_CLOSED";
export const ERROR_MESSAGE_RECEIVED = "ERROR_MESSAGE_RECEIVED";
export const ERROR_MESSAGE_REQUESTED = "ERROR_MESSAGE_REQUESTED";
